# Generated by Django 3.1.2 on 2020-11-30 13:01

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import upsets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateTimeField(auto_now_add=True)),
                ('ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=1000)),
                ('main_character', models.CharField(blank=True, max_length=100, null=True)),
                ('played_sets_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.CharField(max_length=1000)),
                ('winner_characters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=upsets.models.empty_array, size=None)),
                ('loser_characters', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=upsets.models.empty_array, size=None)),
                ('winner_score', models.IntegerField(blank=True, null=True)),
                ('loser_score', models.IntegerField(blank=True, null=True)),
                ('round_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('best_of', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='UpsetTreeNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_depth', models.IntegerField()),
                ('batch_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upsets.batchupdate')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upsets.upsettreenode')),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='upsets.player')),
                ('upset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upsets.set')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1000)),
                ('obsolete', models.BooleanField(default=False)),
                ('date_last_checked', models.DateTimeField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upsets.player')),
            ],
        ),
        migrations.AddIndex(
            model_name='tournament',
            index=models.Index(fields=['-start_date'], name='upsets_tour_start_d_e6907b_idx'),
        ),
        migrations.AddField(
            model_name='set',
            name='batch_update',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upsets.batchupdate'),
        ),
        migrations.AddField(
            model_name='set',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loses', to='upsets.player'),
        ),
        migrations.AddField(
            model_name='set',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='upsets.tournament'),
        ),
        migrations.AddField(
            model_name='set',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='upsets.player'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upsets.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='upsettreenode',
            unique_together={('player', 'batch_update')},
        ),
        migrations.AddIndex(
            model_name='twittertag',
            index=models.Index(fields=['player'], name='upsets_twit_player__a19925_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='twittertag',
            unique_together={('tag', 'player')},
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['tag', '-played_sets_count'], name='upsets_play_tag_ae58d1_idx'),
        ),
    ]
