# Generated by Django 3.1.2 on 2020-10-31 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('winner_score', models.IntegerField()),
                ('looser_score', models.IntegerField()),
                ('round_name', models.CharField(max_length=200)),
                ('best_of', models.IntegerField(blank=True, null=True)),
                ('looser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='looser', to='upsets.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upsets.tournament')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='upsets.player')),
            ],
        ),
    ]
