# Generated by Django 3.1.2 on 2020-11-30 16:31

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
