# Generated by Django 3.1.2 on 2020-11-30 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0002_auto_20201130_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsettreenode',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upsets.player'),
        ),
    ]
