# Generated by Django 3.1.2 on 2020-12-01 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0003_auto_20201130_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsettreenode',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='upsets.upsettreenode'),
        ),
        migrations.AlterField(
            model_name='upsettreenode',
            name='upset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='upsets.set'),
        ),
    ]
