# Generated by Django 3.1.2 on 2020-12-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0004_auto_20201201_0933'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='upsettreenode',
            index=models.Index(fields=['batch_update', 'player'], name='upsets_upse_batch_u_c6cf5f_idx'),
        ),
    ]
