# Generated by Django 3.1.2 on 2020-11-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0004_auto_20201101_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpsetTreeNode',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='upsets.player')),
                ('node_depth', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upsets.upsettreenode')),
                ('upset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='upsets.set')),
            ],
        ),
    ]
