# Generated by Django 3.1.2 on 2020-11-17 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0007_auto_20201116_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1000)),
                ('obsolete', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upsets.player')),
            ],
            options={
                'unique_together': {('tag', 'player')},
            },
        ),
    ]
