# Generated by Django 3.1.2 on 2020-11-17 18:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0008_twittertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='set',
            name='looser_characters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='set',
            name='winner_characters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
