# Generated by Django 3.1.2 on 2020-12-10 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0009_auto_20201210_1346'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BatchUpdate',
            new_name='TreeContainer',
        ),
    ]
