# Generated by Django 3.1.2 on 2020-12-10 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0011_auto_20201210_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upsettreenode',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='upsets.player'),
        ),
        migrations.AlterField(
            model_name='upsettreenode',
            name='upset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='upsets.set'),
        ),
    ]
