# Generated by Django 3.1.2 on 2020-11-17 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0011_auto_20201117_1903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='set',
            old_name='looser_characters',
            new_name='loser_characters',
        ),
        migrations.RenameField(
            model_name='set',
            old_name='looser_score',
            new_name='loser_score',
        ),
        migrations.RemoveField(
            model_name='set',
            name='looser',
        ),
        migrations.AddField(
            model_name='set',
            name='loser',
            field=models.ForeignKey(default=222927, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='upsets.player'),
            preserve_default=False,
        ),
    ]
