# Generated by Django 3.1.2 on 2020-11-18 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0012_auto_20201117_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='upsets.tournament'),
        ),
        migrations.AddField(
            model_name='player',
            name='main_character',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='set',
            name='loser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loses', to='upsets.player'),
        ),
        migrations.AlterField(
            model_name='set',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='upsets.tournament'),
        ),
        migrations.AlterField(
            model_name='set',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='upsets.player'),
        ),
    ]
