# Generated by Django 3.1.2 on 2020-12-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0012_auto_20201210_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='online',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
