# Generated by Django 3.1.2 on 2020-12-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0013_tournament_online'),
    ]

    '''
    When we changed the primary key type of Sets (from auto incremented
    integer to charfield) the django migration didn't update the foreign key id
    type field in upsets_upsettreenode, we do it manually.
    '''

    operations = [
        migrations.RunSQL('ALTER TABLE upsets_upsettreenode ALTER COLUMN upset_id TYPE VARCHAR(1000);')
    ]
