# Generated by Django 3.1.2 on 2020-11-18 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0013_auto_20201118_1024'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='played_sets_count',
            field=models.IntegerField(default=0),
        ),
    ]
