# Generated by Django 3.1.2 on 2020-11-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0014_player_played_sets_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['-played_sets_count'], name='upsets_play_played__871f4d_idx'),
        ),
    ]
