# Generated by Django 3.1.2 on 2020-11-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0015_auto_20201118_1718'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='player',
            name='upsets_play_played__871f4d_idx',
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['tag', '-played_sets_count'], name='upsets_play_tag_ae58d1_idx'),
        ),
    ]
