# Generated by Django 3.1.2 on 2020-11-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upsets', '0016_auto_20201130_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='twittertag',
            name='date_last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='twittertag',
            index=models.Index(fields=['player'], name='upsets_twit_player__a19925_idx'),
        ),
    ]
